"""rename address

Revision ID: 9273eb1dfc7a
Revises: c6afcec720ef
Create Date: 2024-07-03 10:51:52.546805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9273eb1dfc7a'
down_revision = 'c6afcec720ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
